# Generated by Django 5.2.6 on 2025-09-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postcomment_level_postcomment_lft_postcomment_rght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='posts.postcomment'),
        ),
    ]
