# Generated by Django 5.2.6 on 2025-09-11 12:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_created_at_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b39be95-6481-4723-96b8-84aa502713db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b39be95-6481-4723-96b8-84aa502713db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b39be95-6481-4723-96b8-84aa502713db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b39be95-6481-4723-96b8-84aa502713db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
