# Generated by Django 5.2.6 on 2025-09-12 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_created_at_post_updated_at_alter_commentlike_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a11bf564-b183-462a-b419-e07d28817e4b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a11bf564-b183-462a-b419-e07d28817e4b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a11bf564-b183-462a-b419-e07d28817e4b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a11bf564-b183-462a-b419-e07d28817e4b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
