# Generated by Django 5.2.6 on 2025-09-09 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecf53f21-2e21-47e4-a7e1-8f9d27e4c7fb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecf53f21-2e21-47e4-a7e1-8f9d27e4c7fb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
