# Generated by Django 5.2.6 on 2025-09-09 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18faef07-f57a-4463-b218-6f617ee38a54'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18faef07-f57a-4463-b218-6f617ee38a54'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
