# Generated by Django 5.2.6 on 2025-09-09 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('967c68d6-dfe7-4211-bf31-494d131da1b0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('967c68d6-dfe7-4211-bf31-494d131da1b0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
