# Generated by Django 5.2.6 on 2025-09-09 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b5ecda6-f98b-4321-b2f5-5f085f8d6cbd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b5ecda6-f98b-4321-b2f5-5f085f8d6cbd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
