# Generated by Django 5.2.6 on 2025-09-10 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57bedf8d-8a75-45d2-b736-c4ea14ba487d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57bedf8d-8a75-45d2-b736-c4ea14ba487d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
