# Generated by Django 5.2.6 on 2025-09-10 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userconfirmation_is_confirmed_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a07cb76-4dde-419e-92ea-e4a5148bc3c4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a07cb76-4dde-419e-92ea-e4a5148bc3c4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
