# Generated by Django 5.2.6 on 2025-09-11 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24ffa923-4719-45ee-95b6-63a9156abc84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24ffa923-4719-45ee-95b6-63a9156abc84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
