# Generated by Django 5.2.6 on 2025-09-11 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93d10e44-9a84-451e-a728-e332decb19fe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93d10e44-9a84-451e-a728-e332decb19fe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
