# Generated by Django 5.2.6 on 2025-09-11 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01ea76a0-da41-40a8-80f3-3d8c373166be'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01ea76a0-da41-40a8-80f3-3d8c373166be'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
