# Generated by Django 5.2.6 on 2025-09-11 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8114160a-65be-4338-8210-73d5745e8d22'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8114160a-65be-4338-8210-73d5745e8d22'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
