# Generated by Django 5.2.6 on 2025-09-11 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e62e5389-2062-4ec1-b13f-a13c032e7b78'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e62e5389-2062-4ec1-b13f-a13c032e7b78'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
