# Generated by Django 5.2.6 on 2025-09-11 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('818319e6-f711-4961-934c-028735d276ec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('818319e6-f711-4961-934c-028735d276ec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
