# Generated by Django 5.2.6 on 2025-09-11 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b39be95-6481-4723-96b8-84aa502713db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b39be95-6481-4723-96b8-84aa502713db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
