# Generated by Django 5.2.6 on 2025-09-12 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a11bf564-b183-462a-b419-e07d28817e4b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a11bf564-b183-462a-b419-e07d28817e4b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
