# Generated by Django 5.2.6 on 2025-09-12 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1a24db6-e388-486c-91f9-d47a6f076cd7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1a24db6-e388-486c-91f9-d47a6f076cd7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
