# Generated by Django 5.2.6 on 2025-09-12 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f153086d-caec-48ce-b073-66c10aea5dee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f153086d-caec-48ce-b073-66c10aea5dee'), editable=False, primary_key=True, serialize=False),
        ),
    ]
