services:
    api:
        container_name: instagram_clone
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        env_file:
            - .env
